### PR TITLE
Visual Studio Project for EEMBC SecureMark-TLS Benchmark

### PR DESCRIPTION
**Pull request by hannestschofenig**
Plus added code to make it compile under Windows

### CODE REVIEW

**Comment by petertorelli** [comment]
Hi Hannes,

Thanks for creating the PR for the VisualStudio project. Also thanks for catching the memset bug and the type size issues. 

The paths aren't correct in the project file: I cloned the repo, opened the project, and got a few dozen "cannot find file..." errors, most due to the wrong path for "mbedtls/config.h". If you clone this branch to a new folder, do you see these errors?

Thanks,
Peter

**Comment by petertorelli** [comment]
Whoops, nevermind, I was building "Release" but you only configured "Debug".

**Comment by hannestschofenig** [comment]
I forgot to also include the include dirs and the pre-processor directives in the release version. I updated the code.

**Comment by petertorelli** [comment]
Looks good. At some point in the future I'd like to make everything modular with `cmake` but I think many VisualStudio users work from the GUI and not with `cmake`. Thanks!

**Pull request merged**
