### PR TITLE
example selfhosted using wolfSSL

### PR DESCRIPTION
**Pull request by JacobBarthelmeh**
Adds build of the example selfhosted with linking to a wolfSSL library.

Items left, that need input on:
The CRC fails for ECC sign and verify because wolfSSL is not using a deterministic ECC sign. There is the macro WOLFSSL_GENSEED_FORTEST in wolfSSL that will generate the same random number each run but the ECC sign operation would still not be the same as MBEDTLS_ECDSA_DETERMINISTIC.

Results of running the example selfhosted benchmark on 2.5 GHz Quad-Core Intel Core i7

| MBEDTLS   (default bundled with securemark-tls) |
| -- |
| Running each primitive for at   least 10s or 10 iterations.
| Component #00 ips=      1496024.750 crc=0xc7b0 expected_crc=0xc7b0
| Component #01 ips=       983698.062 crc=0x5481 expected_crc=0x5481
| Component #02 ips=       716009.188 crc=0x998a expected_crc=0x998a
| Component #03 ips=       865484.312 crc=0xd82d expected_crc=0xd82d
| Component #04 ips=       447433.594 crc=0x005b expected_crc=0x005b
| Component #05 ips=          547.965 crc=0xb659 expected_crc=0xb659
| Component #06 ips=         1282.158 crc=0x3a47 expected_crc=0x3a47
| Component #07 ips=          384.414 crc=0x3a47 expected_crc=0x3a47
| Component #08 ips=      8081394.500 crc=0x2151 expected_crc=0x2151
| Component #09 ips=      3322021.500 crc=0x3b3c expected_crc=0x3b3c
| Component #10 ips=       532918.938 crc=0x1d3f expected_crc=0x1d3f
| Component #11 ips=        88543.422 crc=0x0000 expected_crc=0x0000
| Component #12 ips=        48076.734 crc=0x9284 expected_crc=0x9284
| Component #13 ips=       115416.336 crc=0x989e expected_crc=0x989e
| SecureMark-TLS Score is   124682.961 marks

| wolfSSL  ./configure   CFLAGS="-DWOLFSSL_AES_DIRECT -DHAVE_AES_ECB" --enable-ecc   --enable-keygen --enable-aesccm --enable-sp --enable-sp-asm --enable-intelasm |
| -- |
| Running each primitive for at   least 10s or 10 iterations.
| Component #00 ips=      4979360.500 crc=0xc7b0 expected_crc=0xc7b0
| Component #01 ips=      4016123.750 crc=0x5481 expected_crc=0x5481
| Component #02 ips=      2964893.250 crc=0x998a expected_crc=0x998a
| Component #03 ips=      2539347.750 crc=0xd82d expected_crc=0xd82d
| Component #04 ips=      1405236.500 crc=0x005b expected_crc=0x005b
| Component #05 ips=        14222.483 crc=0xb659 expected_crc=0xb659
| Component #06 ips=        19247.320 crc=0xfb96 expected_crc=0x3a47 ***ERROR: CRCs did not   match
| Component #07 ips=        11747.046 crc=0x7afd expected_crc=0x3a47 ***ERROR: CRCs did not   match
| Component #08 ips=     14070536.000 crc=0x2151 expected_crc=0x2151
| Component #09 ips=      6387107.000 crc=0x3b3c expected_crc=0x3b3c
| Component #10 ips=      1127409.125 crc=0x1d3f expected_crc=0x1d3f
| Component #11 ips=       175699.125 crc=0x0000 expected_crc=0x0000
| Component #12 ips=       106070.492 crc=0x9284 expected_crc=0x9284
| Component #13 ips=       488775.094 crc=0x989e expected_crc=0x989e
| SecureMark-TLS Score is   2696027.500 marks

### CODE REVIEW

**Comment by petertorelli** [comment]
Hi Jacob,
This is a confirmation that I see the PR and will review and provide feedback in the coming week (or two).
Thanks for submitting!
Peter

**Comment by petertorelli** [comment]
@JacobBarthelmeh,

When we developed the benchmark, we opted to go with deterministic ECC sign/verify. Unfortunately this excludes SDKs without deterministic support. However, a propsal to resolve this imitates the mbedTLS implementation [here](https://github.com/eembc/securemark-tls/blob/5f91e26da69f9ce4c81708958fe35e9445bf4480/examples/selfhosted/profile/th_api/redist/mbedtls/ecdsa.c#L178-L185):

~~~
    /* Use private key and message hash (reduced) to initialize HMAC_DRBG */
    MBEDTLS_MPI_CHK( mbedtls_mpi_write_binary( d, data, grp_len ) );
    MBEDTLS_MPI_CHK( derive_mpi( grp, &h, buf, blen ) );
    MBEDTLS_MPI_CHK( mbedtls_mpi_write_binary( &h, data + grp_len, grp_len ) );
    mbedtls_hmac_drbg_seed_buf( &rng_ctx, md_info, data, 2 * grp_len );

    ret = mbedtls_ecdsa_sign( grp, r, s, d, buf, blen,
                      mbedtls_hmac_drbg_random, &rng_ctx );
~~~

Would something like this be a reasonable fix inside the EEMBC<>wolfSSL ECDSA functions?

I assume your changes to `ee_ecdsa.c` regarding the variable signature size were related to this as well?

Thanks,
Peter

**Comment by JacobBarthelmeh** [comment]
@petertorelli 

Yes, the changes in ee_ecdsa.c had to do with the size of the signature varying from it being non deterministic. Something similar to that code could work. There is an issue with wolfSSL having support for the NIST SHA256 HASH-DRBG versus the HMAC one here. If there was a mbedtls_sha256_drbg_random then it could match up like that, with just giving a set seed value.

Maybe if using a custom RNG function in place of mbedtls_hmac_drbg_random we could get the exact same results from both libraries.

```
int deterministic_rng(void * pt, unsigned char * out, size_t sz)
{
  int i;
  static unsigned char r = 0;

  for (i = 0; i < sz; i++)
    out[i] = r++;
  return 0; //or the success value mbedtls is looking for
}

    ret = mbedtls_ecdsa_sign( grp, r, s, d, buf, blen,
                      deterministic_rng, &rng_ctx );
```

That same override function could be used in wolfSSL with defining CUSTOM_RAND_GENERATE_BLOCK. The only problem I see here is it removes the HASH-DRBG algorithm which could throw off the benchmark values.

Regards,
Jacob

**Comment by petertorelli** [comment]
Unfortunately both the self-hosted mode and the official Host UI perform checking that expects HMAC DRBG, so both will fail. Since we cannot change the benchmark (we're working on version 2 right now that inspects TLSv1.3, among other things), I think the clearest path is to leverage the mbedTLS HMAC DRBG function source, itself. The actual execution of the primitive dwarfs the setup costs, so I don't think the performance hit is significant. What do you think?

**Comment by petertorelli** [comment]
It looks like merging in the HMAC DRBG code from mbedTLS needs to be done at wolfcrypt compile time, and is nontrivial when using `CUSTOM_RAND_GENERATE_BLOCK`. I need to discuss further with the working group. I like the idea of using your simple DRBG for both libraries. I think as long as both libraries generate the CRCs this might be OK.

**Comment by eembc** [comment]
Whoops, I renamed the branch as part of a compliance request and appeared to have killed the PR. My bad.

**Comment by JacobBarthelmeh** [comment]
@eembc , no worries. I can reopen it on "main".

@petertorelli
Thinking more about this the set random value would have to be the same value every time, to avoid issues of if mbedtls for example had a buffer 1 size larger than wolfSSL when creating the random information and then called it again later for some other portion of the operation. The count would be off by 1 in this case between the testing RNGs. Have you considered an approach similar to what FIPS does for government compliance (https://csrc.nist.gov/CSRC/media/Projects/Cryptographic-Algorithm-Validation-Program/documents/dss2/ecdsa2vs.pdf) and then just having it be non deterministic for the benchmark after it passes the tests?

Regards,
Jacob

**Pull request closed without merging**
