### PR TITLE
example selfhosted using wolfSSL

### PR DESCRIPTION
**Pull request by JacobBarthelmeh**
Reopening from https://github.com/eembc/securemark-tls/pull/1

### CODE REVIEW

**Comment by petertorelli** [comment]
Hi @JacobBarthelmeh,

I have some updates. I'm pursuing two simultaneous paths: Path 1 is getting wolfSSL running on Arm devices + mbed-os so that I can port to a large number of devices quickly; Path 2 is addressing Det ECDSA according to the RFC.

Path 1. I'm porting to some STM boards, so I cross-compiled wolfSSL for Arm using GCC_ARM and the additional settings from the wolfSSL user guide. I'm running into a failure to generate an RNG. Here is a transcript from the Host UI runner application when SecureMark has been ported to an embedded device:

~~~
000020.043: [io]: m-dut-passthrough(bench-ecdsa-0-1)
000020.055: [io]: m-ready
000020.129: [io]: [dut]: m-ecdsa_sign-iterations-1
000020.133: [emon]: m-[DUT trigger ignored (EMON timer disabled)]
000020.149: [io]: [dut]: m-ecdsa_sign-start
000020.186: [io]: [dut]: d-[Calling wolfCrypt_Init()]
000020.215: [io]: [dut]: d-[Finished wolfCrypt_Init()]
000020.276: [io]: [dut]: e-[Failed to create RNG for ECC signing: -0xc7]
~~~

This is the "verify" phase of the benchmark, where I run a single iteration of each crypto primitive for later proof-of-work validation. Here I'm seeing a failure to create RNG.

This is my compile command for the library:

~~~
./configure \
    --host=arm-none-eabi \
    --disable-examples \
    --prefix=/home/ptorelli/installs/wolfssl-4.5.0/redist \
    CC=arm-none-eabi-gcc \
    LD=arm-none-eabi-ld \
    AR=arm-none-eabi-ar \
    RANLIB=arm-none-eabi-ranlib \
    CFLAGS="-DWOLFSSL_AES_DIRECT -DHAVE_AES_ECB -DNO_WOLFSSL_DIR -DWOLFSSL_USER_IO -DNO_WRITEV -mcpu=cortex-m4 -mthumb -Os -specs=rdimon.specs" CPPFLAGS="-I./" \
    --enable-ecc \
    --enable-keygen \
    --enable-aesccm \
    --enable-sp \
    --enable-sp-asm
~~~

I'm testing on an NUCLEO-L476RG since it is my "old-faithful" platform, it is an M4.

(Note: I had to comment out line 224 because I think mbed-os defines USE_HAL_DRIVER which causes a conflict:
~~~
#ifdef WOLFSSL_USER_SETTINGS
    #include "user_settings.h"
#elif defined(USE_HAL_DRIVER) && !defined(HAVE_CONFIG_H)
    /* STM Configuration File (generated by CubeMX) */
//    #include "wolfSSL.wolfSSL_conf.h"
#endif
~~~

Any ideas what I may have missed?

Path 2. I met with my work group again. They don't want to change the benchmark, and would like to see the [RFC6979](https://tools.ietf.org/html/rfc6979) implemented for the benchmark. I've started on that task, trying to custom-compile wolfSSL to allow me to use a custom DRBG, but this is slow going and I may need an assist. But we can revisit this after we figure out what is wrong in Part 1.

**Comment by JacobBarthelmeh** [comment]
Hi @petertorelli, Happy new year!

For the RNG fail I think it has to do with the underlying source of entropy. Looks like the NUCLEO-L476RG is part of the STM32L4 family? Adding the macro define WOLFSSL_STM32L4 will turn on settings for STM32L4. With the current configure shown it is falling back to the default linux/unix attempt to open /dev/urandom when seeding the RNG and then failing. An example configure with adding WOLFSSL_STM32L4 would be:

```
./configure \
    --host=arm-none-eabi \
    --disable-examples \
    --prefix=/home/ptorelli/installs/wolfssl-4.5.0/redist \
    CC=arm-none-eabi-gcc \
    LD=arm-none-eabi-ld \
    AR=arm-none-eabi-ar \
    RANLIB=arm-none-eabi-ranlib \
    CFLAGS="-DWOLFSSL_STM32L4 -DWOLFSSL_AES_DIRECT -DHAVE_AES_ECB -DNO_WOLFSSL_DIR -DWOLFSSL_USER_IO -DNO_WRITEV -mcpu=cortex-m4 -mthumb -Os -specs=rdimon.specs" CPPFLAGS="-I./" \
    --enable-ecc \
    --enable-keygen \
    --enable-aesccm \
    --enable-sp \
    --enable-sp-asm

```

If the defines do not quite match up with the NUCLEO build then the macro WOLFSSL_GENSEED_FORTEST could be used instead. The only thing is that with the macro WOLFSSL_GENSEED_FORTEST it is a dummy source of entropy (1,2,3...n) and used only for testing, not production.

For item 2, I'm happy to assist with any questions and build settings that come up.

Sorry for the delay on response.
Regards,
Jacob

**Comment by petertorelli** [comment]
Hi @JacobBarthelmeh,

Thanks for the suggestions!

Let's focus on Part 1 for now. 

I started going down the STM32L4 path but it then requires links & config to the CubeMX project, which I don't have, so I tried to solve the warnings by manually copying files over. I abandoned this effort because it felt like I was just hacking at it.

(Question for later: Did you do this for all of the 12+ platforms you benchmarked? I think my workflow might be missing some key steps, because that seems like a lot of work. I'm wondering if I should be building WolfCrypt with the project, instead of in a different directory and copying over the lib*.a file.)

Instead, I switched to `WOLFSSL_GENSEED_FORTEST`, and I even got the friendly reminder:

~~~
  CC       wolfcrypt/src/src_libwolfssl_la-sha.lo
wolfcrypt/src/random.c:2602:10: warning: #warning "write a real random seed!!!!, just for testing now" [-Wcpp]
         #warning "write a real random seed!!!!, just for testing now"
          ^~~~~~~
 ~~~

...I assume this means it compiled correctly. However, I am still seeing the same failure and error code:

~~~
000672.015: >> Running command #24: io dut bench-ecdsa-0-1 (Timeout: 60s, #Stamps: 0)
000672.028: [io]: m-dut-passthrough(bench-ecdsa-0-1)
000672.041: [io]: m-ready
000672.115: [io]: [dut]: m-ecdsa_sign-iterations-1
000672.135: [io]: [dut]: m-ecdsa_sign-start
000672.172: [io]: [dut]: d-[Calling wolfCrypt_Init()]
000672.201: [io]: [dut]: d-[Finished wolfCrypt_Init()]
000672.262: [io]: [dut]: e-[Failed to create RNG for ECC signing: -0xc7]
000672.266: >! Error: Command #24 generated an error
000672.267: >! Error: Command #24 Failed
000672.269: PostHookManager: Stopping EMON trace
~~~

Thanks!
Peter

**Comment by JacobBarthelmeh** [comment]
Hi @petertorelli ,

You are correct, that warning is expected -- letting users know the entropy source set is just a testing one. Maybe it is an issue of the wolfssl/options.h found versus how the library is configured. When building with CMake there should be a couple of print outs for the WOLFSSL_INCLUDE and WOLFSSL_LIB:

```
cmake -DWOLFSSL=1 .. 
-- The C compiler identification is AppleClang 11.0.3.11030032
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc - skipped
-- Detecting C compile features
-- Detecting C compile features - done
WOLFSSL_INCLUDE = /usr/local/include
WOLFSSL_LIB = /usr/local/lib/libwolfssl.dylib
```

Can you check that the wolfssl/options.h found in the WOLFSSL_INCLUDE directory matches that of the wolfssl/options.h in the directory that the wolfssl library was built? Here it would be "cat /usr/local/include/wolfssl/options.h" and comparing that to the wolfssl/options.h from the directory the library was built in. If they mismatch it can cause issues.

Regards,
Jacob

**Comment by petertorelli** [comment]
Hi @JacobBarthelmeh,

I completely wiped all of my work areas and started again (using configure with `--prefix=<some local dir>`). And it works now, I'm able to run on a the L476 and measure energy and performance with the official test framework! This is a big deal, I'm glad we finally have that path cleared.

Also note, I am using the `...FORTEST` variable. I still had to comment out line 224 is `settings.h` because I'm not using CubeMx.

```
#elif defined(USE_HAL_DRIVER) && !defined(HAVE_CONFIG_H)
    /* STM Configuration File (generated by CubeMX) */
    //#include "wolfSSL.wolfSSL_conf.h"
#endif
```

Now I have a WolfSSL version compiled for Cortex-M4 using `gcc-arm-none-eabi`. I also have a license for their AC6 which I will use shortly, which means I can test on other Arm devices by changing the `CFLAGS` targets (we can talk about other non-Arm architectures later).

With that solved, I'd like to return to item No. 2, deterministic ECDSA as RFC6979. In the previous pull request you stated "There is an issue with wolfSSL having support for the NIST SHA256 HASH-DRBG". Does this imply that det. ECDSA cannot be implemented per the RFC fundamentally?

Peter

**Comment by JacobBarthelmeh** [comment]
Hi @petertorelli,

That is great news with the build running on the device!

For item 2. We support NIST SHA256 HASH-DRBG not the HMAC version that MBED TLS is using. That RFC makes mention of using HMAC DRBG in a couple of places, but I think it gives an alternative also for it. I've been thinking some on the deterministic values with signing and hope that we can use the macro WOLFSSL_ECDSA_SET_K when building wolfSSL and call the function wc_ecc_sign_set_k from the th_ecdsa.c file with having generated the k value from RFC6979 process. I plan to take a closer look and attempt that this week.

Regards,
Jacob

**Comment by hannestschofenig** [comment]
Hey Jacob, 

RFC 6979, which defines the deterministic ECDSA, uses the HMAC-DRBG pseudorandom number generator, described in NIST SP800-90A. There is no other option. 

So, if you want to support deterministic ECDSA you will have to implement the HMAC-DRBG.

**Comment by JacobBarthelmeh** [comment]
As an update on this, we started some code for following RFC 6979 with the generation of the k value last week. I do not have an ETA on it but it is in progress.

Regards,
Jacob

**Comment by petertorelli** [comment]
@JacobBarthelmeh,
Thanks for the update!

**Comment by JacobBarthelmeh** [comment]
Hi @petertorelli , we have a deterministic k generation for ECC sign under review https://github.com/wolfSSL/wolfssl/pull/3878. I have tested that the 'crc' result is as expected with the new wolfSSL build. Once it finishes code review and is merged then I will update this PR.
~jacob

**Comment by petertorelli** [comment]
@JacobBarthelmeh,
That is fantastic news! I'm looking forward to re-starting the power/performance study with the Wolf library, I think this will be incredibly useful research.
Peter

**Comment by petertorelli** [comment]
Good news everyone: Wolf has implemented ECDSA and can now run
SecureMark-TLS! Now Jacob and I can re-start our power study in Q2.

[image: image.png]

**Comment by petertorelli** [comment]
@JacobBarthelmeh,
I wanted to follow up on the March 15th comment, has there been an update on the PR supporting detECDSA?
Thanks,
Peter

**Comment by JacobBarthelmeh** [comment]
Hi @petertorelli the wolfSSL pull request finished being reviewed recently and was merged into wolfSSL master branch. wolfSSL version 4.8.0 and newer supports deterministic ECC operations now. Thanks for your patience on this, will try to get this pull request rebased and ready to be reviewed soon.

**Comment by JacobBarthelmeh** [comment]
Hi @petertorelli , rebased the pull request and tested it with the new deterministic ecdsa feature in wolfSSL. On MacOS it looks like all the checks passed :

```
$ ./sec-tls 
Running each primitive for at least 10s or 10 iterations.
Component #00 ips=    1477622.375 crc=0xc7b0 expected_crc=0xc7b0
Component #01 ips=     980629.500 crc=0x5481 expected_crc=0x5481
Component #02 ips=     688214.812 crc=0x998a expected_crc=0x998a
Component #03 ips=    1221112.875 crc=0xd82d expected_crc=0xd82d
Component #04 ips=     510237.438 crc=0x005b expected_crc=0x005b
Component #05 ips=      13556.150 crc=0xb659 expected_crc=0xb659
Component #06 ips=      14978.578 crc=0x3a47 expected_crc=0x3a47
Component #07 ips=      12810.479 crc=0x3a47 expected_crc=0x3a47
Component #08 ips=    8834618.000 crc=0x2151 expected_crc=0x2151
Component #09 ips=    3804048.750 crc=0x3b3c expected_crc=0x3b3c
Component #10 ips=     588447.125 crc=0x1d3f expected_crc=0x1d3f
Component #11 ips=      99838.234 crc=0x0000 expected_crc=0x0000
Component #12 ips=      54748.562 crc=0x9284 expected_crc=0x9284
Component #13 ips=     117603.805 crc=0x989e expected_crc=0x989e
SecureMark-TLS Score is 2028303.750 marks
Disclaimer: this is not an official score. In order to submit an
official score, please contact support@eembc.org.
```

**Comment by petertorelli** [comment]
Fantastic! This is great news. I'll switch to back to email and pick up the thread from ages ago when we first started discussing how to do a broader power survey. Thanks for seeing this through.

**Comment by petertorelli** [comment]
Edit: let me download this PR and do some regression before merging. I should have it done early next week.

**Comment by petertorelli** [comment]
Finished testing selfhsoted on Ubuntu 18/20 & macOS. Now on to embedded!

**Pull request merged**
